Resources:
 Ec2Instance:
  Type: AWS::EC2::Instance
  Properties:
    SecurityGroups:
      - !Ref InstanceSecurityGroup
    KeyName: udacitykey
    ImageId: 'ami-042e8287309f5df03' # you may need to find out what instance types are available in your region - use https://cloud-images.ubuntu.com/locator/ec2/


