version: 2.1
jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: ensure backend infastructure exist
          command: |
            aws cloudformation deploy
              --template-file deploy \
              --stack-name my-stack
workflow:
  my_workflow:
    jobs:
      - create_infrastructure
       


  